# Generated by Django 3.2 on 2021-04-22 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('ursername', models.CharField(max_length=128)),
                ('function', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_secretaireEces', models.BooleanField(default=False)),
                ('is_secretaireCacsup', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebourreEces',
            fields=[
                ('numero_ec', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_creation_ec', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date création')),
                ('montant_ec', models.IntegerField()),
                ('beneficiaire_ec', models.CharField(max_length=128)),
                ('Motif_ec', models.CharField(max_length=128)),
                ('Ligne_bugdetaire_ec', models.CharField(max_length=128)),
                ('secretaire_ec', models.ForeignKey(default='is_secretaireEces', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
