# Generated by Django 3.2 on 2021-04-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_account_cacsup_eces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debourre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ec', models.CharField(max_length=128)),
                ('date_creation_ec', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création')),
                ('montant_ec', models.IntegerField()),
                ('beneficiaire_ec', models.CharField(max_length=128)),
                ('motif_ec', models.CharField(max_length=128)),
                ('ligne_bugdetaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSecretaire', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cacsup',
            name='secretaire',
        ),
        migrations.RemoveField(
            model_name='eces',
            name='secretaire',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Cacsup',
        ),
        migrations.DeleteModel(
            name='Eces',
        ),
        migrations.AddField(
            model_name='debourre',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.secretaire'),
        ),
    ]
